### ISSUE TITLE
Clause to allow switching royalty distribution mechanisms

### ISSUE THREAD

**Issue by aquabu** [aquabu/peer-production-royalty-token-license#11]
It's possible that a blockchain will fail or that a new technology will emerge with superior properties. If that occurs the license should allow transference of the royalty token table.

This one may and should make folks nervous as it's where trust in the human legal system and trust in the math of the blockchain may intersect.

**Comment by jesseposner** [comment]
I added the following provision to the Modifications section to address this issue:

"The Core Contributors may, by a majority vote, modify (1) the Royalty Payment Address or (2) the currency or method by which the Royalties are paid. The Core Contributors shall promptly revise this agreement to reflect any such modification."
