### ISSUE TITLE
What jursidiction should the license be governed in?

### ISSUE THREAD

**Issue by aquabu** [aquabu/peer-production-royalty-token-license#14]
Is it advantageous to select a jurisdiction based on limited liability, associations rights to hold assets, etc?

**Comment by jesseposner** [comment]
Selecting a specific jurisdiction could prejudice parties that aren't located in that jurisdiction, so I suggest using the following open-ended approach which I added in 6ae99813c5176664cf0256382ac5041348202636:

> Any action or suit relating to this agreement may be brought only in the courts of a jurisdiction wherein the party resides or in which the party conducts its primary business, and under the laws of that jurisdiction excluding its conflict-of-law provisions. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. Any use of the Intellectual Property outside the scope of this agreement or after its termination will be subject to the requirements and penalties of the U.S. Copyright Act, 17 U.S.C. 101 et seq., the equivalent laws of other countries, and international treaty.
