### ISSUE TITLE
Clarify Royalty Revenue scoping

### ISSUE THREAD

**Issue by aquabu** [aquabu/peer-production-royalty-token-license#18]
Royalties should be applicable to revenue derived from the use of the licensed software. 
- It shouldn't apply to all of an organizations gross revenue (that would be unusable)
- It shouldn't be easily dodgable by charging for a related service and offering swarmbot for free

**Comment by jesseposner** [comment]
The royalties are limited to "Gross Sales Revenue," which only includes revenue received from the "sale of the Intellectual Property."

The definition refers to "derivatives, modifications, sublicensing, and integrations" as an attempt to include indirect uses.

> “Gross Sales Revenue” means all revenues actually received by You from the sale of the Intellectual Property, including any derivatives, modifications, sublicensing, and integrations of the Intellectual Property.
