### ISSUE TITLE
IP Agreement for contributors

### ISSUE THREAD

**Issue by aquabu** [aquabu/peer-production-royalty-token-license#5]
Should include
- a [contributor license agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement)
- maintain rights to the IP they contribute in other contexts similar to the [Twitter innovators patent agreement](https://github.com/twitter/innovators-patent-agreement)?

**Comment by jesseposner** [comment]
The dynamic royalty license agreement currently contains the rights and obligations for both users and contributors, so a separate contributor agreement is probably not necessary. I'll take a look at the Twitter patent agreement and make some recommendations for integrating similar provisions.

**Comment by aquabu** [comment]
@jesseposner The IP agreement is coming up a lot lately. Any new thoughts on this? The contributor license frequently also requires that the user has the right to grant IP when it is granted. This protects all contributors from having their code base poisoned by dependencies on IP that could cause law suits.

**Comment by aquabu** [comment]
@jesseposner also contributors should be free to reuse their contributions in other repositories.

**Comment by jesseposner** [comment]
@aquabu The second paragraph of the "Grant of License" section is meant to address the contributor license and the contributor's right to grant the IP when it is granted:

> "If You are a Contributor, You agree to the grant of the above license with respect to your contributions to the Software, and You represent that You are legally entitled to grant the above license. If Your employer has rights to intellectual property that You create that includes Your contributions, You represent that You have received permission to make contributions on behalf of that employer under this agreement."

The license granted is "non-exclusive," which preserves the right of each contributor to reuse the contribution in other repositories.

**Comment by aquabu** [comment]
Great!
