### ISSUE TITLE
Support multiple contribution valuation protocols

### ISSUE THREAD

**Issue by aquabu** [aquabu/peer-production-royalty-token-license#7]
Valuing work is a complex topic and may require some variations. The agreement should be flexible enough to change and accommodate multiple protocols.

**Comment by jesseposner** [comment]
This might already be addressed by the following provision of the Modifications section:

"The Core Contributors may, by a majority vote, modify [. . .] the criteria and metrics for determining royalty token awards, for versions of the Software created subsequent to such modification. "

**Comment by aquabu** [comment]
That works for now. We need to look at the role of voting for core contributors, how many they are, if we need delegates.
