### ISSUE TITLE
Improve governance structure based on swarm DCO model

### ISSUE THREAD

**Issue by aquabu** [aquabu/peer-production-royalty-token-license#9]
Thanks to @fractastical (Joel) for this comment.

There was a lot of work done on Distributed Collaborative Organizations that should be integrated into the governance model by:
- Joel Dietz, Swarm
- Greg Xethalis, Katten
- Primavera de Filippi, Harvard / LOVE
- Jim Hazard, Common Accord

Here's a link to the Swarm DCO license:
https://swarm.gitbooks.io/dco-book/content/dco-model-template.html

**Comment by jesseposner** [comment]
@aquabu I just uploaded a first draft of the governance agreement.
